### ISSUE TITLE
gitignore kullanirsaniz iyi olur

### ISSUE THREAD

**Issue by TheYkk** [diloabininyeri/php-mvc-framework#1]
git ignore ile .idea ve vendor klasorlerini ignorlayabilirsiniz

**Comment by diloabininyeri** [comment]
Tabiki cok eski bir calisma simdi yazsam oooo

**Comment by TheYkk** [comment]
farketmemisim pardon

**Comment by gdemir** [comment]
Rails tadında : http://barak-framework.github.io
